### ISSUE TITLE
File About Sym1n0

### ISSUE THREAD

**Issue by xrkk** [L1NNA/L1nna.github.io#1]
Do you still share the pdf file <Sym1n0: large-scale symbolic expression retrieval for cross-architecture assembly clone search>? I searched the internet and just can't find it.
Thank you!

**Comment by steven-hh-ding** [comment]
sorry we just saw this message. unfortunately the paper is currently under view; so we don't have a public copy yet...

**Comment by xrkk** [comment]
> sorry we just saw this message. unfortunately the paper is currently under view; so we don't have a public copy yet...

Ok, I understand.
